// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: internal/api/sagaspecpb/spec.proto

package sagaspecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Saga struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Steps []*Step `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
}

func (x *Saga) Reset() {
	*x = Saga{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_sagaspecpb_spec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Saga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Saga) ProtoMessage() {}

func (x *Saga) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_sagaspecpb_spec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Saga.ProtoReflect.Descriptor instead.
func (*Saga) Descriptor() ([]byte, []int) {
	return file_internal_api_sagaspecpb_spec_proto_rawDescGZIP(), []int{0}
}

func (x *Saga) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dependencies     []string `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Task             *Task    `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	CompensatingTask *Task    `protobuf:"bytes,4,opt,name=compensating_task,json=compensatingTask,proto3" json:"compensating_task,omitempty"`
}

func (x *Step) Reset() {
	*x = Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_sagaspecpb_spec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_sagaspecpb_spec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_internal_api_sagaspecpb_spec_proto_rawDescGZIP(), []int{1}
}

func (x *Step) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Step) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Step) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *Step) GetCompensatingTask() *Task {
	if x != nil {
		return x.CompensatingTask
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Input map[string]string `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_sagaspecpb_spec_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_sagaspecpb_spec_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_internal_api_sagaspecpb_spec_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetInput() map[string]string {
	if x != nil {
		return x.Input
	}
	return nil
}

var File_internal_api_sagaspecpb_spec_proto protoreflect.FileDescriptor

var file_internal_api_sagaspecpb_spec_proto_rawDesc = []byte{
	0x0a, 0x22, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x61, 0x67, 0x61, 0x73, 0x70, 0x65, 0x63, 0x70, 0x62, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x61, 0x67, 0x61, 0x73, 0x70, 0x65, 0x63, 0x22, 0x39, 0x0a, 0x04, 0x53,
	0x61, 0x67, 0x61, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x61, 0x67, 0x61, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52,
	0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x22, 0xb5, 0x01, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x69, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x61, 0x67, 0x61, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04,
	0x74, 0x61, 0x73, 0x6b, 0x12, 0x48, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x61, 0x67, 0x61, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x10, 0x63, 0x6f,
	0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x92,
	0x01, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3c, 0x0a, 0x05, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x61, 0x67, 0x61, 0x73, 0x70,
	0x65, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x72, 0x6e, 0x6f, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x6f, 0x76, 0x2f, 0x73, 0x6f, 0x65,
	0x67, 0x75, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x73, 0x61, 0x67, 0x61, 0x73, 0x70, 0x65, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_api_sagaspecpb_spec_proto_rawDescOnce sync.Once
	file_internal_api_sagaspecpb_spec_proto_rawDescData = file_internal_api_sagaspecpb_spec_proto_rawDesc
)

func file_internal_api_sagaspecpb_spec_proto_rawDescGZIP() []byte {
	file_internal_api_sagaspecpb_spec_proto_rawDescOnce.Do(func() {
		file_internal_api_sagaspecpb_spec_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_sagaspecpb_spec_proto_rawDescData)
	})
	return file_internal_api_sagaspecpb_spec_proto_rawDescData
}

var file_internal_api_sagaspecpb_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_api_sagaspecpb_spec_proto_goTypes = []any{
	(*Saga)(nil), // 0: internal.api.sagaspec.Saga
	(*Step)(nil), // 1: internal.api.sagaspec.Step
	(*Task)(nil), // 2: internal.api.sagaspec.Task
	nil,          // 3: internal.api.sagaspec.Task.InputEntry
}
var file_internal_api_sagaspecpb_spec_proto_depIdxs = []int32{
	1, // 0: internal.api.sagaspec.Saga.steps:type_name -> internal.api.sagaspec.Step
	2, // 1: internal.api.sagaspec.Step.task:type_name -> internal.api.sagaspec.Task
	2, // 2: internal.api.sagaspec.Step.compensating_task:type_name -> internal.api.sagaspec.Task
	3, // 3: internal.api.sagaspec.Task.input:type_name -> internal.api.sagaspec.Task.InputEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_api_sagaspecpb_spec_proto_init() }
func file_internal_api_sagaspecpb_spec_proto_init() {
	if File_internal_api_sagaspecpb_spec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_sagaspecpb_spec_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Saga); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_sagaspecpb_spec_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_sagaspecpb_spec_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_sagaspecpb_spec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_sagaspecpb_spec_proto_goTypes,
		DependencyIndexes: file_internal_api_sagaspecpb_spec_proto_depIdxs,
		MessageInfos:      file_internal_api_sagaspecpb_spec_proto_msgTypes,
	}.Build()
	File_internal_api_sagaspecpb_spec_proto = out.File
	file_internal_api_sagaspecpb_spec_proto_rawDesc = nil
	file_internal_api_sagaspecpb_spec_proto_goTypes = nil
	file_internal_api_sagaspecpb_spec_proto_depIdxs = nil
}
